# Generated by Django 5.2.1 on 2025-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='projects',
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='skills', to='projects.tag'),
        ),
    ]
